M48
; DRILL file {KiCad (6.0.4)} date Fri Jul 21 11:29:49 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-21T11:29:49+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.360
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X66.973Y45.75
X66.973Y33.55
X66.998Y65.842
X66.998Y53.642
T2
X21.615Y40.503
X21.615Y30.263
T0
M30
